name: Build and Push to ECR on Develop

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: fleetman-organization-mnad/fleetman-webapp
  AWS_ROLE: arn:aws:iam::491085414331:role/PushToECR
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # for OIDC login

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build JAR with Maven
        run: mvn clean package --batch-mode

      - name: List contents of target directory
        run: ls -lh target/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        run: |
          IMAGE_URI=491085414331.dkr.ecr.eu-north-1.amazonaws.com/fleetman-organization-mnad/fleetman-webapp
          docker build -t $IMAGE_URI:$GITHUB_SHA .
          docker push $IMAGE_URI:$GITHUB_SHA
