name: Build and Push to ECR on master

on:
  push:
    branches:
      - master

env:
  AWS_REGION: eu-north-1
  AWS_ROLE: arn:aws:iam::491085414331:role/PushToECR
  IMAGE_URI: 491085414331.dkr.ecr.eu-north-1.amazonaws.com/fleetman-organization-mnad/fleetman-api-gateway

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # for OIDC login

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build JAR with Maven
        run: mvn clean package --batch-mode

      - name: List contents of target directory
        run: ls -lh target/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Prepare image tags
        id: prep
        run: |
          BRANCH=${GITHUB_REF##*/}
          TS=$(date +%s)
          REVISION=${GITHUB_SHA::8}
          BUILD_ID="${BRANCH}-${REVISION}-${TS}"
          LATEST_ID=canary
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            BUILD_ID=${GITHUB_REF/refs\/tags\//}
            LATEST_ID=latest
          fi
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "BUILD_ID=${BUILD_ID}" >> $GITHUB_ENV
          echo "LATEST_ID=${LATEST_ID}" >> $GITHUB_ENV

      - name: Build, tag, and push Docker image
        run: |
          docker build -t $IMAGE_URI:$GITHUB_SHA .
          docker push $IMAGE_URI:$GITHUB_SHA

      - name: Show pushed image tags
        run: |
          echo "Pushed image tags:"
          echo " - $IMAGE_URI:$BUILD_ID"
          echo " - $IMAGE_URI:$LATEST_ID"
